/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Color,
} from './interface';
import {
  CheckboxChangeEventDetail,
} from './components/checkbox/checkbox-interface';

export namespace Components {
  interface GrmButton {
    'color'?: Color;
    'disabled'?: boolean;
  }
  interface GrmCheckbox {
    'checked': boolean;
    'disabled': boolean;
    'label'?: string;
    /**
    * The name of the control, which is submitted with the form data
    */
    'name'?: string;
    'value': string;
  }
  interface GrmInput {
    'autocomplete'?: string;
    'disabled'?: boolean;
    'name'?: string;
    'placeholder'?: string;
    'type'?: string;
    'value'?: string;
  }
}

declare global {


  interface HTMLGrmButtonElement extends Components.GrmButton, HTMLStencilElement {}
  var HTMLGrmButtonElement: {
    prototype: HTMLGrmButtonElement;
    new (): HTMLGrmButtonElement;
  };

  interface HTMLGrmCheckboxElement extends Components.GrmCheckbox, HTMLStencilElement {}
  var HTMLGrmCheckboxElement: {
    prototype: HTMLGrmCheckboxElement;
    new (): HTMLGrmCheckboxElement;
  };

  interface HTMLGrmInputElement extends Components.GrmInput, HTMLStencilElement {}
  var HTMLGrmInputElement: {
    prototype: HTMLGrmInputElement;
    new (): HTMLGrmInputElement;
  };
  interface HTMLElementTagNameMap {
    'grm-button': HTMLGrmButtonElement;
    'grm-checkbox': HTMLGrmCheckboxElement;
    'grm-input': HTMLGrmInputElement;
  }
}

declare namespace LocalJSX {
  interface GrmButton {
    'color'?: Color;
    'disabled'?: boolean;
  }
  interface GrmCheckbox {
    'checked'?: boolean;
    'disabled'?: boolean;
    'label'?: string;
    /**
    * The name of the control, which is submitted with the form data
    */
    'name'?: string;
    /**
    * Emitted when the checkbox loses focus.
    */
    'onGrmBlur'?: (event: CustomEvent<void>) => void;
    'onGrmChange'?: (event: CustomEvent<CheckboxChangeEventDetail>) => void;
    /**
    * Emitted when the checkbox has focus.
    */
    'onGrmFocus'?: (event: CustomEvent<void>) => void;
    'value'?: string;
  }
  interface GrmInput {
    'autocomplete'?: string;
    'disabled'?: boolean;
    'name'?: string;
    'placeholder'?: string;
    'type'?: string;
    'value'?: string;
  }

  interface IntrinsicElements {
    'grm-button': GrmButton;
    'grm-checkbox': GrmCheckbox;
    'grm-input': GrmInput;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'grm-button': LocalJSX.GrmButton & JSXBase.HTMLAttributes<HTMLGrmButtonElement>;
      'grm-checkbox': LocalJSX.GrmCheckbox & JSXBase.HTMLAttributes<HTMLGrmCheckboxElement>;
      'grm-input': LocalJSX.GrmInput & JSXBase.HTMLAttributes<HTMLGrmInputElement>;
    }
  }
}


