/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Color,
} from './interface';

export namespace Components {
  interface GrmButton {
    'color'?: Color;
    'disabled'?: boolean;
  }
  interface GrmInput {
    'autocomplete'?: string;
    'disabled'?: boolean;
    'name'?: string;
    'placeholder'?: string;
    'type'?: string;
    'value'?: string;
  }
}

declare global {


  interface HTMLGrmButtonElement extends Components.GrmButton, HTMLStencilElement {}
  var HTMLGrmButtonElement: {
    prototype: HTMLGrmButtonElement;
    new (): HTMLGrmButtonElement;
  };

  interface HTMLGrmInputElement extends Components.GrmInput, HTMLStencilElement {}
  var HTMLGrmInputElement: {
    prototype: HTMLGrmInputElement;
    new (): HTMLGrmInputElement;
  };
  interface HTMLElementTagNameMap {
    'grm-button': HTMLGrmButtonElement;
    'grm-input': HTMLGrmInputElement;
  }
}

declare namespace LocalJSX {
  interface GrmButton {
    'color'?: Color;
    'disabled'?: boolean;
  }
  interface GrmInput {
    'autocomplete'?: string;
    'disabled'?: boolean;
    'name'?: string;
    'placeholder'?: string;
    'type'?: string;
    'value'?: string;
  }

  interface IntrinsicElements {
    'grm-button': GrmButton;
    'grm-input': GrmInput;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'grm-button': LocalJSX.GrmButton & JSXBase.HTMLAttributes<HTMLGrmButtonElement>;
      'grm-input': LocalJSX.GrmInput & JSXBase.HTMLAttributes<HTMLGrmInputElement>;
    }
  }
}


